server:
    port: 10302
    max-http-header-size: 1024000
spring:
    application:
        name: box-admin-api
    profiles:
        active: dev
    datasource:
        # \u4F7F\u7528druid\u6570\u636E\u6E90
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
## \u8BE5\u914D\u7F6E\u8282\u70B9\u4E3A\u72EC\u7ACB\u7684\u8282\u70B9\uFF0C\u5982\u679C\u5C06\u8FD9\u4E2A\u914D\u7F6E\u653E\u5728spring\u7684\u8282\u70B9\u4E0B\uFF0C\u5BFC\u81F4\u914D\u7F6E\u65E0\u6CD5\u88AB\u8BC6\u522B
mybatis-plus:
#   \u5982\u679C\u662F\u653E\u5728src/main/java\u76EE\u5F55\u4E0B classpath:/com/ifec/api/shop/mapper/*Mapper.xml
#   \u5982\u679C\u662F\u653E\u5728resource\u76EE\u5F55 classpath:/mapper/*Mapper.xml
#    mapper-locations: classpath:/mapper/*Mapper.xml
    mapper-locations: classpath*:/com/kuose/box/*/**/mapper/*Mapper.xml
    typeAliasesPackage: com.kuose.box.*.*.entity
    global-config:
        #\u4E3B\u952E\u7C7B\u578B  0:"\u6570\u636E\u5E93ID\u81EA\u589E", 1:"\u7528\u6237\u8F93\u5165ID",2:"\u5168\u5C40\u552F\u4E00ID (\u6570\u5B57\u7C7B\u578B\u552F\u4E00ID)", 3:"\u5168\u5C40\u552F\u4E00ID UUID";
        id-type: 0
        #\u5B57\u6BB5\u7B56\u7565 0:"\u5FFD\u7565\u5224\u65AD",1:"\u975E NULL \u5224\u65AD"),2:"\u975E\u7A7A\u5224\u65AD"
        field-strategy: 2
         #\u9A7C\u5CF0\u4E0B\u5212\u7EBF\u8F6C\u6362
        db-column-underline: true
        #\u5237\u65B0mapper \u8C03\u8BD5\u795E\u5668
        refresh-mapper: true
    configuration:
        #\u914D\u7F6E\u8FD4\u56DE\u6570\u636E\u5E93(column\u4E0B\u5212\u7EBF\u547D\u540D&&\u8FD4\u56DEjava\u5B9E\u4F53\u662F\u9A7C\u5CF0\u547D\u540D)\uFF0C\u81EA\u52A8\u5339\u914D\u65E0\u9700as\uFF08\u6CA1\u5F00\u542F\u8FD9\u4E2A\uFF0CSQL\u9700\u8981\u5199as\uFF1A select user_id as userId\uFF09
        map-underscore-to-camel-case: true
        cache-enabled: false
        call-setters-on-nulls: true
logging:
    config: classpath:conf/logback.xml




litemall:
  # \u5F00\u53D1\u8005\u5E94\u8BE5\u8BBE\u7F6E\u6210\u81EA\u5DF1\u7684wx\u76F8\u5173\u4FE1\u606F
  wx:
    app-id: wx82794a3bb64be941
    app-secret: e634ecdb5c1edcd51c800ff24471aa4f
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify
    # \u5546\u6237\u8BC1\u4E66\u6587\u4EF6\u8DEF\u5F84
    # \u8BF7\u53C2\u8003\u201C\u5546\u6237\u8BC1\u4E66\u201D\u4E00\u8282 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx

  #\u901A\u77E5\u76F8\u5173\u914D\u7F6E
  notify:
    # \u77ED\u6D88\u606F\u6A21\u7248\u901A\u77E5\u914D\u7F6E
    # \u77ED\u4FE1\u606F\u7528\u4E8E\u901A\u77E5\u5BA2\u6237\uFF0C\u4F8B\u5982\u53D1\u8D27\u77ED\u4FE1\u901A\u77E5\uFF0C\u6CE8\u610F\u914D\u7F6E\u683C\u5F0F\uFF1Btemplate-name\uFF0Ctemplate-templateId \u8BF7\u53C2\u8003 NotifyType \u679A\u4E3E\u503C
    sms:
      enable: true
      appid: 1400231207
      appkey: 4377279bfad6a4c8c8daaa7ad97b1065
      template:
      - name: paySucceed
        templateId: 372171
      - name: captcha
        templateId: 372171

  # \u5BF9\u8C61\u5B58\u50A8\u914D\u7F6E
  storage:
    # \u5F53\u524D\u5DE5\u4F5C\u7684\u5BF9\u8C61\u5B58\u50A8\u6A21\u5F0F\uFF0C\u5206\u522B\u662Flocal\u3001aliyun\u3001tencent\u3001qiniu
    active: aliyun
    # \u963F\u91CC\u4E91\u5BF9\u8C61\u5B58\u50A8\u914D\u7F6E\u4FE1\u606F
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: xxx
      accessKeySecret: xxxx
      bucketName: kuose

---
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://192.168.5.176:3306/box?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
---
spring:
    profiles: test
    datasource:
        url: jdbc:mysql://192.168.5.176:3306/box?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
---
spring:
    profiles: pre-product
    datasource:
        url: jdbc:mysql://localhost:3306/box?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
---
spring:
    profiles: product
    datasource:
        url: jdbc:mysql://localhost:3306/box?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
